(function($){Drupal.behaviors.viewsSlideshowCycle={attach:function(context){$('.views_slideshow_cycle_main:not(.viewsSlideshowCycle-processed)',context).addClass('viewsSlideshowCycle-processed').each(function(){var fullId='#'+$(this).attr('id');var settings=Drupal.settings.viewsSlideshowCycle[fullId];settings.targetId='#'+$(fullId+" :first").attr('id');settings.slideshowId=settings.targetId.replace('#views_slideshow_cycle_teaser_section_','');var pager_after_fn=function(curr,next,opts){var slideNum=opts.currSlide;if(typeof settings.processedAfter=='undefined'||!settings.processedAfter){settings.processedAfter=1;slideNum=(typeof settings.opts.startingSlide=='undefined')?0:settings.opts.startingSlide;}
if(settings.pause_after_slideshow){opts.counter+=1;if(opts.counter==settings.num_divs+1){opts.counter=1;Drupal.viewsSlideshow.action({"action":'pause',"slideshowID":settings.slideshowId,"force":true});}}
Drupal.viewsSlideshow.action({"action":'transitionEnd',"slideshowID":settings.slideshowId,"slideNum":slideNum});}
var pager_before_fn=function(curr,next,opts){$(document).trigger('drupal:views_slideshow_cycle:before',{curr:curr,next:next,opts:opts,settings:settings});var slideNum=opts.nextSlide;if(settings.remember_slide){createCookie(settings.vss_id,slideNum,settings.remember_slide_days);}
if(!settings.fixed_height){var $ht=$(next).height();$(next).parent().animate({height:$ht});}
if(typeof settings.processedBefore=='undefined'||!settings.processedBefore){settings.processedBefore=1;slideNum=(typeof opts.startingSlide=='undefined')?0:opts.startingSlide;}
Drupal.viewsSlideshow.action({"action":'transitionBegin',"slideshowID":settings.slideshowId,"slideNum":slideNum});}
settings.loaded=false;settings.opts={speed:settings.speed,timeout:settings.timeout,delay:settings.delay,sync:settings.sync,random:settings.random,nowrap:settings.nowrap,pause_after_slideshow:settings.pause_after_slideshow,counter:0,after:pager_after_fn,before:pager_before_fn,cleartype:(settings.cleartype)?true:false,cleartypeNoBg:(settings.cleartypenobg)?true:false}
if(settings.remember_slide){var startSlide=readCookie(settings.vss_id);if(startSlide==null){startSlide=0;}
settings.opts.startingSlide=parseInt(startSlide);}
if(settings.effect=='none'){settings.opts.speed=1;}
else{settings.opts.fx=settings.effect;}
var hash=location.hash;if(hash){var hash=hash.replace('#','');var aHash=hash.split(';');var aHashLen=aHash.length;for(var i=0;i<aHashLen;i++){var initialInfo=aHash[i].split(':');if(settings.slideshowId==initialInfo[0]&&settings.num_divs>initialInfo[1]){settings.opts.startingSlide=parseInt(initialInfo[1]);}}}
if(settings.pause){var mouseIn=function(){Drupal.viewsSlideshow.action({"action":'pause',"slideshowID":settings.slideshowId});}
var mouseOut=function(){Drupal.viewsSlideshow.action({"action":'play',"slideshowID":settings.slideshowId});}
if(jQuery.fn.hoverIntent){$('#views_slideshow_cycle_teaser_section_'+settings.vss_id).hoverIntent(mouseIn,mouseOut);}
else{$('#views_slideshow_cycle_teaser_section_'+settings.vss_id).hover(mouseIn,mouseOut);}}
if(settings.play_on_hover){var mouseIn=function(){Drupal.viewsSlideshow.action({"action":'play',"slideshowID":settings.slideshowId,"force":true});}
var mouseOut=function(){Drupal.viewsSlideshow.action({"action":'pause',"slideshowID":settings.slideshowId});}
if(jQuery.fn.hoverIntent){$('#views_slideshow_cycle_teaser_section_'+settings.vss_id).hoverIntent(mouseIn,mouseOut);}
else{$('#views_slideshow_cycle_teaser_section_'+settings.vss_id).hover(mouseIn,mouseOut);}}
if(settings.pause_on_click){$('#views_slideshow_cycle_teaser_section_'+settings.vss_id).click(function(){Drupal.viewsSlideshow.action({"action":'pause',"slideshowID":settings.slideshowId,"force":true});});}
if(typeof JSON!='undefined'){var advancedOptions=JSON.parse(settings.advanced_options);for(var option in advancedOptions){switch(option){case"activePagerClass":case"allowPagerClickBubble":case"autostop":case"autostopCount":case"backwards":case"bounce":case"cleartype":case"cleartypeNoBg":case"containerResize":case"continuous":case"delay":case"easeIn":case"easeOut":case"easing":case"fastOnEvent":case"fit":case"fx":case"manualTrump":case"metaAttr":case"next":case"nowrap":case"pager":case"pagerEvent":case"pause":case"pauseOnPagerHover":case"prev":case"prevNextEvent":case"random":case"randomizeEffects":case"requeueOnImageNotLoaded":case"requeueTimeout":case"rev":case"slideExpr":case"slideResize":case"speed":case"speedIn":case"speedOut":case"startingSlide":case"sync":case"timeout":var optionValue=advancedOptions[option];optionValue=Drupal.viewsSlideshowCycle.advancedOptionCleanup(optionValue);settings.opts[option]=optionValue;break;case"width":var optionValue=advancedOptions["width"];optionValue=Drupal.viewsSlideshowCycle.advancedOptionCleanup(optionValue);settings.opts["width"]=optionValue;settings.opts["containerResize"]=0;break;case"height":var optionValue=advancedOptions["height"];optionValue=Drupal.viewsSlideshowCycle.advancedOptionCleanup(optionValue);settings.opts["height"]=optionValue;settings.fixed_height=1;break;case"animIn":case"animInDelay":case"animOut":case"animOutDelay":case"cssBefore":case"cssAfter":case"shuffle":var cssValue=advancedOptions[option];cssValue=Drupal.viewsSlideshowCycle.advancedOptionCleanup(cssValue);settings.opts[option]=eval('('+cssValue+')');break;case"after":var afterValue=advancedOptions[option];afterValue=Drupal.viewsSlideshowCycle.advancedOptionCleanup(afterValue);settings.opts[option]=function(currSlideElement,nextSlideElement,options,forwardFlag){pager_after_fn(currSlideElement,nextSlideElement,options);eval(afterValue);}
break;case"before":var beforeValue=advancedOptions[option];beforeValue=Drupal.viewsSlideshowCycle.advancedOptionCleanup(beforeValue);settings.opts[option]=function(currSlideElement,nextSlideElement,options,forwardFlag){pager_before_fn(currSlideElement,nextSlideElement,options);eval(beforeValue);}
break;case"end":var endValue=advancedOptions[option];endValue=Drupal.viewsSlideshowCycle.advancedOptionCleanup(endValue);settings.opts[option]=function(options){eval(endValue);}
break;case"fxFn":var fxFnValue=advancedOptions[option];fxFnValue=Drupal.viewsSlideshowCycle.advancedOptionCleanup(fxFnValue);settings.opts[option]=function(currSlideElement,nextSlideElement,options,afterCalback,forwardFlag){eval(fxFnValue);}
break;case"onPagerEvent":var onPagerEventValue=advancedOptions[option];onPagerEventValue=Drupal.viewsSlideshowCycle.advancedOptionCleanup(onPagerEventValue);settings.opts[option]=function(zeroBasedSlideIndex,slideElement){eval(onPagerEventValue);}
break;case"onPrevNextEvent":var onPrevNextEventValue=advancedOptions[option];onPrevNextEventValue=Drupal.viewsSlideshowCycle.advancedOptionCleanup(onPrevNextEventValue);settings.opts[option]=function(isNext,zeroBasedSlideIndex,slideElement){eval(onPrevNextEventValue);}
break;case"pagerAnchorBuilder":var pagerAnchorBuilderValue=advancedOptions[option];pagerAnchorBuilderValue=Drupal.viewsSlideshowCycle.advancedOptionCleanup(pagerAnchorBuilderValue);settings.opts[option]=function(index,DOMelement){var returnVal='';eval(pagerAnchorBuilderValue);return returnVal;}
break;case"pagerClick":var pagerClickValue=advancedOptions[option];pagerClickValue=Drupal.viewsSlideshowCycle.advancedOptionCleanup(pagerClickValue);settings.opts[option]=function(zeroBasedSlideIndex,slideElement){eval(pagerClickValue);}
break;case"paused":var pausedValue=advancedOptions[option];pausedValue=Drupal.viewsSlideshowCycle.advancedOptionCleanup(pausedValue);settings.opts[option]=function(cont,opts,byHover){eval(pausedValue);}
break;case"resumed":var resumedValue=advancedOptions[option];resumedValue=Drupal.viewsSlideshowCycle.advancedOptionCleanup(resumedValue);settings.opts[option]=function(cont,opts,byHover){eval(resumedValue);}
break;case"timeoutFn":var timeoutFnValue=advancedOptions[option];timeoutFnValue=Drupal.viewsSlideshowCycle.advancedOptionCleanup(timeoutFnValue);settings.opts[option]=function(currSlideElement,nextSlideElement,options,forwardFlag){var returnVal=settings.timeout;eval(timeoutFnValue);return returnVal;}
break;case"updateActivePagerLink":var updateActivePagerLinkValue=advancedOptions[option];updateActivePagerLinkValue=Drupal.viewsSlideshowCycle.advancedOptionCleanup(updateActivePagerLinkValue);settings.opts[option]=function(pager,currSlideIndex){eval(updateActivePagerLinkValue);}
break;}}}
if(settings.wait_for_image_load){settings.totalImages=$(settings.targetId+' img').length;if(settings.totalImages){settings.loadedImages=0;$(settings.targetId+' img').each(function(){var $imageElement=$(this);$imageElement.bind('load',function(){Drupal.viewsSlideshowCycle.imageWait(fullId);});var imgSrc=$imageElement.attr('src');$imageElement.attr('src','');$imageElement.attr('src',imgSrc);});setTimeout("Drupal.viewsSlideshowCycle.load('"+fullId+"')",settings.wait_for_image_load_timeout);}
else{Drupal.viewsSlideshowCycle.load(fullId);}}
else{Drupal.viewsSlideshowCycle.load(fullId);}});}};Drupal.behaviors.viewsSlideshowSwipe={attach:function(context){var isTouch=(('ontouchstart'in window)||(navigator.msMaxTouchPoints>0));if(isTouch===true&&$('.views-slideshow-cycle-main-frame').length){var $slider=$('.views-slideshow-cycle-main-frame'),opts={start:{x:0,y:0},end:{x:0,y:0},hdiff:0,vdiff:0,length:0,angle:null,direction:null,},optsReset=$.extend(true,{},opts),H_THRESHOLD=110,V_THRESHOLD=50;$slider.data('bw',opts).bind('touchstart.cycle',function(e){var touch=e.originalEvent.touches[0]||e.originalEvent.changedTouches[0];if(e.originalEvent.touches.length==1){var data=$(this).data('bw');data.start.x=touch.pageX;data.start.y=touch.pageY;$(this).data('bw',data);}}).bind('touchend.cycle',function(e){var touch=e.originalEvent.touches[0]||e.originalEvent.changedTouches[0];var data=$(this).data('bw');data.end.x=touch.pageX;data.end.y=touch.pageY;$(this).data('bw',data);if(data.start.x!=0&&data.start.y!=0){data.vdiff=data.start.x-data.end.x;data.hdiff=data.end.y-data.start.y;if(Math.abs(data.vdiff)==data.start.x&&Math.abs(data.hdiff)==data.start.y){data.vdiff=0;data.hdiff=0;}
var length=Math.round(Math.sqrt(Math.pow(data.vdiff,2)+Math.pow(data.hdiff,2)));var rads=Math.atan2(data.hdiff,data.vdiff);var angle=Math.round(rads*180/Math.PI);if(angle<0){angle=360-Math.abs(angle);}
if(length>H_THRESHOLD&&V_THRESHOLD>data.hdiff){e.preventDefault();if(angle>135&&angle<225){var cyopt=$slider.data('cycle.opts');if(cyopt.currSlide>0){$slider.cycle((cyopt.currSlide-1),'scrollRight');}
else{$slider.cycle((cyopt.slideCount-1),'scrollRight');}}
else if(angle>315||angle<45){$slider.cycle('next');}}}
data=$.extend(true,{},optsReset);});}}};Drupal.viewsSlideshowCycle=Drupal.viewsSlideshowCycle||{};Drupal.viewsSlideshowCycle.advancedOptionCleanup=function(value){value=$.trim(value);value=value.replace(/\n/g,'');if(value.match(/^[\d.]+%$/)){}
else if(!isNaN(parseInt(value))){value=parseInt(value);}
else if(value.toLowerCase()=='true'){value=true;}
else if(value.toLowerCase()=='false'){value=false;}
return value;}
Drupal.viewsSlideshowCycle.imageWait=function(fullId){if(++Drupal.settings.viewsSlideshowCycle[fullId].loadedImages==Drupal.settings.viewsSlideshowCycle[fullId].totalImages){Drupal.viewsSlideshowCycle.load(fullId);}};Drupal.viewsSlideshowCycle.load=function(fullId){var settings=Drupal.settings.viewsSlideshowCycle[fullId];if(!settings.loaded){$(settings.targetId).cycle(settings.opts);$(settings.targetId).parent().parent().addClass('views-slideshow-cycle-processed');settings.loaded=true;if(settings.start_paused){Drupal.viewsSlideshow.action({"action":'pause',"slideshowID":settings.slideshowId,"force":true});}
if(settings.pause_when_hidden){var checkPause=function(settings){var visible=viewsSlideshowCycleIsVisible(settings.targetId,settings.pause_when_hidden_type,settings.amount_allowed_visible);if(visible){Drupal.viewsSlideshow.action({"action":'play',"slideshowID":settings.slideshowId});}
else{Drupal.viewsSlideshow.action({"action":'pause',"slideshowID":settings.slideshowId});}}
$(window).scroll(function(){checkPause(settings);});$(window).resize(function(){checkPause(settings);});}}};Drupal.viewsSlideshowCycle.pause=function(options){try{if(options.pause_in_middle&&$.fn.pause){$('#views_slideshow_cycle_teaser_section_'+options.slideshowID).pause();}
else{$('#views_slideshow_cycle_teaser_section_'+options.slideshowID).cycle('pause');}}
catch(e){if(!e instanceof TypeError){throw e;}}};Drupal.viewsSlideshowCycle.play=function(options){Drupal.settings.viewsSlideshowCycle['#views_slideshow_cycle_main_'+options.slideshowID].paused=false;if(options.pause_in_middle&&$.fn.resume){$('#views_slideshow_cycle_teaser_section_'+options.slideshowID).resume();}
else{$('#views_slideshow_cycle_teaser_section_'+options.slideshowID).cycle('resume');}};Drupal.viewsSlideshowCycle.previousSlide=function(options){$('#views_slideshow_cycle_teaser_section_'+options.slideshowID).cycle('prev');};Drupal.viewsSlideshowCycle.nextSlide=function(options){$('#views_slideshow_cycle_teaser_section_'+options.slideshowID).cycle('next');};Drupal.viewsSlideshowCycle.goToSlide=function(options){$('#views_slideshow_cycle_teaser_section_'+options.slideshowID).cycle(options.slideNum);};function IsNumeric(sText){var ValidChars="0123456789";var IsNumber=true;var Char;for(var i=0;i<sText.length&&IsNumber==true;i++){Char=sText.charAt(i);if(ValidChars.indexOf(Char)==-1){IsNumber=false;}}
return IsNumber;}
function createCookie(name,value,days){if(days){var date=new Date();date.setTime(date.getTime()+(days*24*60*60*1000));var expires="; expires="+date.toGMTString();}
else{var expires="";}
document.cookie=name+"="+value+expires+"; path=/";}
function readCookie(name){var nameEQ=name+"=";var ca=document.cookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==' ')c=c.substring(1,c.length);if(c.indexOf(nameEQ)==0){return c.substring(nameEQ.length,c.length);}}
return null;}
function eraseCookie(name){createCookie(name,"",-1);}
function viewsSlideshowCycleIsVisible(elem,type,amountVisible){var docViewTop=$(window).scrollTop();var docViewBottom=docViewTop+$(window).height();var docViewLeft=$(window).scrollLeft();var docViewRight=docViewLeft+$(window).width();var elemTop=$(elem).offset().top;var elemHeight=$(elem).height();var elemBottom=elemTop+elemHeight;var elemLeft=$(elem).offset().left;var elemWidth=$(elem).width();var elemRight=elemLeft+elemWidth;var elemArea=elemHeight*elemWidth;var missingLeft=0;var missingRight=0;var missingTop=0;var missingBottom=0;if(elemLeft<docViewLeft){missingLeft=docViewLeft-elemLeft;}
if(elemRight>docViewRight){missingRight=elemRight-docViewRight;}
if(elemTop<docViewTop){missingTop=docViewTop-elemTop;}
if(elemBottom>docViewBottom){missingBottom=elemBottom-docViewBottom;}
if(type=='full'){return((elemBottom>=docViewTop)&&(elemTop<=docViewBottom)&&(elemBottom<=docViewBottom)&&(elemTop>=docViewTop)&&(elemLeft>=docViewLeft)&&(elemRight<=docViewRight)&&(elemLeft<=docViewRight)&&(elemRight>=docViewLeft));}
else if(type=='vertical'){var verticalShowing=elemHeight-missingTop-missingBottom;if(typeof amountVisible==='string'&&amountVisible.indexOf('%')){return(((verticalShowing/elemHeight)*100)>=parseInt(amountVisible));}
else{return(verticalShowing>=parseInt(amountVisible));}}
else if(type=='horizontal'){var horizontalShowing=elemWidth-missingLeft-missingRight;if(typeof amountVisible==='string'&&amountVisible.indexOf('%')){return(((horizontalShowing/elemWidth)*100)>=parseInt(amountVisible));}
else{return(horizontalShowing>=parseInt(amountVisible));}}
else if(type=='area'){var areaShowing=(elemWidth-missingLeft-missingRight)*(elemHeight-missingTop-missingBottom);if(typeof amountVisible==='string'&&amountVisible.indexOf('%')){return(((areaShowing/elemArea)*100)>=parseInt(amountVisible));}
else{return(areaShowing>=parseInt(amountVisible));}}}})(jQuery);