<?php
/**
 * Created by PhpStorm.
 * User: massimomoro
 * Date: 05/06/17
 * Time: 12:51
 */
# Includes the autoloader for libraries installed with composer
require_once 'sites/all/vendor/autoload.php';


# Imports the Google Cloud client library
use Google\Cloud\Storage\StorageClient;
use Google\Cloud\ServiceBuilder;




const DEFAULT_URL = 'https://cmv-gioco.firebaseio.com/';
const DEFAULT_TOKEN = '8Kozhc9q8Hiyazc3mkPMtmDRi4sE4zeDc7kdnSNx';
/* Solo in produzione
const DEFAULT_PATH = '/Events'; */
const DEFAULT_PATH = '/firebase';

function firebase_node_prepare($node) {


    if ($node->type == 'events') {

        drupal_add_js('https://www.gstatic.com/firebasejs/3.6.8/firebase.js', 'external');

    }

}

function firebase_node_presave($node)
{
    if ($node->type == 'events') {

    }
}
function firebase_node_validate($node, $form, &$form_state) {
    if ($node->type == 'events') {

    }
}


function firebase_node_submit($node, $form, &$form_state) {

    if ($node->type == 'events') {


      putenv('GOOGLE_APPLICATION_CREDENTIALS=sites/all/modules/firebase/service-account.json');


      # Your Google Cloud Platform project ID
      $projectId = '250228474323';

      # Instantiates a client
      $storage = new StorageClient([
        'projectId' => $projectId
      ]);
      $bucket = $storage->bucket('cmv-gioco.appspot.com');

    /*  $client = new Google_Client();
      $guzzleClient = new \GuzzleHttp\Client(array( 'curl' => array( CURLOPT_SSL_VERIFYPEER => false, ), ));
      $client->setHttpClient($guzzleClient);
*/
        $eventType = "E";
        $firebase = new \Firebase\FirebaseLib(DEFAULT_URL, DEFAULT_TOKEN);
        $wrapper = entity_metadata_wrapper('node', $node); //Wrapper aggiunto solo se installato il modulo Entity API
        $output  = $wrapper->body->value->value(array('sanitize' => TRUE));
        $description =drupal_html_to_text($node->body['und'][0]['safe_value']);

        $event = array(
            "EndDate" => date('d/m/Y', strtotime($node->field_eventdate['und'][0]['value2'])),
            "EventType" => $eventType,
            "StartDate" => date('d/m/Y', strtotime($node->field_eventdate['und'][0]['value']))
        );
        switch ($node->language) {
            case "en":
                $descriptionTitle = "Description";
                $NameTitle = "Name";
                break;
            case "it":
                $descriptionTitle = "DescriptionIT";
                $NameTitle = "NameIT";
                break;
            case "zh":
                $descriptionTitle = "DescriptionZH";
                $NameTitle = "NameZH";
                break;

        }
        $event[$descriptionTitle] = $description;
        $event[$NameTitle] = $node->title;
        //Controllo per il campo ImageName
        $field = field_get_items('node', $node, 'field_immaginemobile');
        if ($field) {
            $file = file_load($node->field_immaginemobile['und'][0]['fid']);
            $imageName = $file->filename;
            /* Disabilitato su localhost
          $bucket->upload(
            fopen($file->uri, 'r'),
            [
              'name' => 'Events/'.$imageName
            ]
          );*/
        } else {
            $collection_entity_id = $node->field_images_events['und'][0]['value'];
            $full_entity = field_collection_item_load($collection_entity_id);
            $imageName = $full_entity->field_image_event_field['und'][0]['filename'];
            /* Disabilitato su localhost
          $bucket->upload(
            fopen($full_entity->field_image_event_field['und'][0]['uri'], 'r'),
            [
              'name' => 'Events/'.$imageName
            ]
          );*/
        }

        if ($imageName == null) {
            $imageName = "DefaulImageNameMobile.png"; //Se l'evento non ha né immagini né il campo ImmagineMobile allora carica il default
        }
        $event["ImageName"] = $imageName;

        //Controllo per il campo booking
        $fieldBook = field_get_items('node', $node, 'field_eventbrite');
        if ($fieldBook) {
            $event["Book"] = "ON";
            $regex = "/\"(.*)\?r/";
            $str = $node->field_eventbrite['und'][0]['value'];

            if (preg_match($regex, $str,$matches)) {
                // Indeed, the expression "[a-zA-Z]+ \d+" matches the date string
                $event["URLBook"] = $matches[1];

            }
        } else {
            $event["Book"] = "OFF";
        }

        if ($node->field_sede['und'][0]['value'] == 1) {
            $sede = "CN";
        }else {
            $sede = "VE";
        }
        $event["office"] = $sede;
        $images_array = $node->field_images_events;

        if (count($images_array['und'])>0) :
            for ($x = 0; $x <= count($images_array['und'])-1; $x++) {
                if ($x <= 2) { //Controllo se il numero delle immagini è superiore a 3
                    $collection_entity_id = $node->field_images_events['und'][$x]['value'];
                    $full_entity = field_collection_item_load($collection_entity_id);
                    $image_name = $full_entity->field_image_event_field['und'][0]['filename'];
                    $count = $x+1;
                    $event["ImageEvent$count"] = $image_name;
                    /* Disabilitato su local host
                  $bucket->upload(
                    fopen($full_entity->field_image_event_field['und'][0]['uri'], 'r'),
                    [
                      'name' => 'Events/'.$image_name
                    ]
                  );*/
                }

            }
        endif;
        if ($node->translation_source->nid) {
            $firebase->update(DEFAULT_PATH . '/' . $node->translation_source->nid, $event);
        } else {
            if ($node->tnid != 0) {
                $firebase->update(DEFAULT_PATH . '/' . $node->tnid, $event);
            } else{
                $firebase->set(DEFAULT_PATH . '/' . $node->nid, $event);
            }

        }

    }
}

